AWSTemplateFormatVersion: "2010-09-09"
Resources:
  DNS:
    Type: "AWS::Route53::HostedZone"
    Properties:
      HostedZoneConfig:
        Comment: "My hosted zone for subdomain.waitinglist.link"
      HostedZoneTags:
        - Key: Name
          Value: TestValue
      Name: "subdomain.waitinglist.link"

Outputs:
  NameServers:
    Value: !Join [",", !GetAtt DNS.NameServers]
