SHUTDOWN IMMEDIATE;
STARTUP MOUNT;
ALTER DATABSE ACHIVELOG;
ALTER DATABASE OPEN;

ALTER SESSION SET CONTAINER = CDB$ROOT;
ALTER DATABASE FORCE LOGGING;
ALTER DATABASE ADD SUPPLEMENTAL LOG DATA;

CREATE TABLESPACE GG_DATA DATAFILE '/opt/oracle/oradata/ORCLCDB/gg_data.dbf' SIZE 100M AUTOEXTEND ON NEXT 50M MAXSIZE UNLIMITED;

ALTER SESSION SET CONTAINER = ORCLPDB1;
CREATE TABLESPACE GG_DATA DATAFILE '/opt/oracle/oradata/ORCLCDB/ORCLPDB1/gg_data.dbf' SIZE 100M AUTOEXTEND ON NEXT 50M MAXSIZE UNLIMITED;

ALTER SESSION SET CONTAINER = CDB$ROOT;
CREATE USER c##ggadmin IDENTIFIED BY passw0rd CONTAINER=all DEFAULT TABLESPACE GG_DATA TEMPORARY TABLESPACE temp;
GRANT RESOURCE to c##ggadmin;
GRANT CREATE SESSION to c##ggadmin;
GRANT CREATE VIEW to c##ggadmin;
GRANT CREATE TABLE to c##ggadmin;
GRANT CONNECT to c##ggadmin CONTAINER=all; 
-- GRANT DV_GOLDENGATE_ADMIN; -- for data vault user
-- GRANT DV_GOLDENGATE_REDO_ACCESS; -- for data vault user
GRANT ALTER SYSTEM to c##ggadmin;
GRANT ALTER USER to c##ggadmin;
ALTER USER c##ggadmin SET CONTAINER_DATA=all CONTAINER=current;
ALTER USER c##ggadmin QUOTA unlimited ON GG_DATA;
GRANT SELECT ANY DICTIONARY to c##ggadmin;
GRANT SELECT ANY TRANSACTION to c##ggadmin;
EXEC DBMS_GOLDENGATE_AUTH.GRANT_ADMIN_PRIVILEGE('c##ggadmin', CONTAINER => 'ALL');

ALTER SYSTEM SET ENABLE_GOLDENGATE_REPLICATION=true SCOPE=both;
