version: '3'
services:
  source-db:
    platform: linux/x86_64
    build:
      context: ./docker/oracle19c
      dockerfile: Dockerfile
      args:
        DB_EDITION: SE2
    shm_size: 2g
    volumes:
      - ./docker/oracle19c/scripts/setup:/opt/oracle/scripts/setup
      - ./docker/oracle19c/data/source-oradata:/opt/oracle/oradata
  target-ogg:
    platform: linux/x86_64
    build:
      context: ./docker/ogg19c-ma
      dockerfile: Dockerfile
    volumes:
      - ./docker/ogg19c-ma/tns_admin:/opt/oracle/product/19.3.0/client_1/network/admin
      - ./docker/ogg19c-ma/data:/opt/oracle/
    ports:
      - 11000:11000
      - 11001:11001
      - 11002:11002
      - 11003:11003
      - 11004:11004
      - 11005:11005
  target-db:
    platform: linux/x86_64
    build:
      context: ./docker/oracle19c
      dockerfile: Dockerfile
      args:
        DB_EDITION: SE2
    volumes:
      - ./docker/oracle19c/data/target-oradata:/opt/oracle/oradata
