version: "3"
services:
  source-ogg-12-db-12:
    platform: linux/x86_64
    build:
      context: ./docker/oracle12c-ogg12c-ca
      dockerfile: Dockerfile
      shm_size: 256m
    volumes:
      - ./docker/oracle12c-ogg12c-ca/scripts/source-setup:/opt/oracle/scripts/setup
      - ./docker/oracle12c-ogg12c-ca/data/source:/opt/oracle
    ports:
      - 1521:1521
    environment:
      - TARGET_OGG_HOST=target-ogg-proxy
      - TARGET_OGG_PORT=12003
  target-ogg-proxy:
    image: hpello/tcp-proxy
    command: target-ogg-19ma 12003
    environment:
      - LISTEN_PORT=12003
  target-ogg-19ma:
    platform: linux/x86_64
    build:
      context: ./docker/ogg19c-ma
      dockerfile: Dockerfile.RHEL8
    volumes:
      - ./docker/ogg19c-ma/scripts/target-setup:/opt/oracle/scripts/setup
      - ./docker/ogg19c-ma/tns_admin/target:/opt/oracle/product/19.3.0/client_1/network/admin
      - ./docker/ogg19c-ma/data/target:/opt/oracle/ogg_deployments
    environment:
      - PORT_BASE=12000
    ports:
      - 12000:12000
      - 12001:12001
      - 12002:12002
      - 12003:12003
      - 12004:12004
      - 12005:12005
  target-db-19:
    platform: linux/x86_64
    build:
      context: ./docker/oracle19c
      dockerfile: Dockerfile
      args:
        DB_EDITION: SE2
    volumes:
      - ./docker/oracle19c/scripts/target-setup:/opt/oracle/scripts/setup
      - ./docker/oracle19c/data/target:/opt/oracle/oradata
    ports:
      - 1522:1521
