version: "3"
services:
  source-db-19:
    platform: linux/x86_64
    build:
      context: ./docker/oracle19c
      dockerfile: Dockerfile
      args:
        DB_EDITION: EE
    volumes:
      - ./docker/oracle19c/scripts/source-setup:/opt/oracle/scripts/setup
      - ./docker/oracle19c/data/source:/opt/oracle/oradata
    ports:
      - 1521:1521
  source-ogg-19ca:
    platform: linux/x86_64
    build:
      context: ./docker/ogg19c-ca
      dockerfile: Dockerfile.RHEL8
    volumes:
      - ./docker/ogg19c-ca/scripts/source-setup:/opt/oracle/scripts/setup
      - ./docker/ogg19c-ca/tns_admin/source:/opt/oracle/product/19.3.0/client_1/network/admin
      - ./docker/ogg19c-ca/data/source:/opt/oracle/ogg
    environment:
      - TARGET_OGG_HOST=target-ogg-21ma
      - TARGET_OGG_PORT=12003
  target-ogg-21ma:
    platform: linux/x86_64
    build:
      context: ./docker/ogg21c-ma
      dockerfile: Dockerfile
    volumes:
      - ./docker/ogg21c-ma/scripts/target-setup:/opt/oracle/scripts/setup
      - ./docker/ogg21c-ma/tns_admin/target:/opt/oracle/network/admin
      - ./docker/ogg21c-ma/data/target:/opt/oracle/ogg_deployments
    environment:
      - PORT_BASE=12000
    ports:
      - 12000:12000
      - 12001:12001
      - 12002:12002
      - 12003:12003
      - 12004:12004
      - 12005:12005
  target-db-19:
    platform: linux/x86_64
    build:
      context: ./docker/oracle19c
      dockerfile: Dockerfile
      args:
        DB_EDITION: SE2
    volumes:
      - ./docker/oracle19c/scripts/target-setup:/opt/oracle/scripts/setup
      - ./docker/oracle19c/data/target:/opt/oracle/oradata
    ports:
      - 1522:1521
