version: "3"
services:
  source-db-19:
    platform: linux/x86_64
    build:
      context: ./docker/oracle19c
      dockerfile: Dockerfile
      args:
        DB_EDITION: EE
    volumes:
      - ./docker/oracle19c/scripts/source-setup:/opt/oracle/scripts/setup
      - ./docker/oracle19c/data/source-19ca:/opt/oracle/oradata
    ports:
      - 1521:1521
  source-ogg-19ca:
    platform: linux/x86_64
    build:
      context: ./docker/ogg19c-ca
      dockerfile: Dockerfile.RHEL7
    volumes:
      - ./docker/ogg19c-ca/scripts/source-setup:/opt/oracle/scripts/setup
      - ./docker/ogg19c-ca/tns_admin/source:/opt/oracle/product/19.3.0/client_1/network/admin
      - ./docker/ogg19c-ca/data/source-19ca:/opt/oracle/ogg
    environment:
      - TARGET_OGG_HOST=target-ogg-19ca
      - TARGET_OGG_PORT=7809
  target-ogg-19ca:
    platform: linux/x86_64
    build:
      context: ./docker/ogg19c-ca
      dockerfile: Dockerfile.RHEL8
    volumes:
      - ./docker/ogg19c-ca/scripts/target-setup:/opt/oracle/scripts/setup
      - ./docker/ogg19c-ca/tns_admin/target:/opt/oracle/product/19.3.0/client_1/network/admin
      - ./docker/ogg19c-ca/data/target-19ca:/opt/oracle/ogg
  target-db-19:
    platform: linux/x86_64
    build:
      context: ./docker/oracle19c
      dockerfile: Dockerfile
      args:
        DB_EDITION: SE2
    volumes:
      - ./docker/oracle19c/scripts/target-setup:/opt/oracle/scripts/setup
      - ./docker/oracle19c/data/target-19ca:/opt/oracle/oradata
    ports:
      - 1522:1521
