version: "3"
services:
  source-db:
    platform: linux/x86_64
    build:
      context: ./docker/oracle19c
      dockerfile: Dockerfile
      args:
        DB_EDITION: EE
    volumes:
      - ./docker/oracle19c/scripts/source-setup:/opt/oracle/scripts/setup
      - ./docker/oracle19c/data/source-oradata:/opt/oracle/oradata
    ports:
      - 1521:1521
  source-ogg-ca:
    platform: linux/x86_64
    build:
      context: ./docker/ogg19c-ca
      dockerfile: Dockerfile
    volumes:
      - ./docker/ogg19c-ca/tns_admin/source-admin:/opt/oracle/product/19.3.0/client_1/network/admin
      - ./docker/ogg19c-ca/data/source-ogg:/opt/oracle/ogg
  target-ogg-ca:
    platform: linux/x86_64
    build:
      context: ./docker/ogg19c-ca
      dockerfile: Dockerfile
    volumes:
      - ./docker/ogg19c-ca/tns_admin/target-admin:/opt/oracle/product/19.3.0/client_1/network/admin
      - ./docker/ogg19c-ca/data/target-ogg:/opt/oracle/ogg
  target-db:
    platform: linux/x86_64
    build:
      context: ./docker/oracle19c
      dockerfile: Dockerfile
      args:
        DB_EDITION: SE2
    volumes:
      - ./docker/oracle19c/scripts/target-setup:/opt/oracle/scripts/setup
      - ./docker/oracle19c/data/target-oradata:/opt/oracle/oradata
    ports:
      - 1522:1521
