AWSTemplateFormatVersion: 2010-09-09

Parameters:
  VpcName:
    Type: String
    Default: intra-vpc

  OggInstanceIpAddress:
    Type: String
    Default: 172.16.0.4

Resources:
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: OGG Security Group
      VpcId: !ImportValue intra-vpc-VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 0
          ToPort: 65535
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: !Sub ${VpcName}-ogg-security-group-${AWS::Region}

  EC2IAMRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore

  EC2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles:
        - !Ref EC2IAMRole

  OggInstanceKeyPair:
    Type: AWS::EC2::KeyPair
    Properties:
      KeyName: !Sub ${AWS::StackName}-OggInstanceKeyPair

  OggInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-087bd73fc10ea41af
      InstanceType: t2.micro
      KeyName: !Ref OggInstanceKeyPair
      IamInstanceProfile: !Ref EC2InstanceProfile
      PrivateIpAddress: !Ref OggInstanceIpAddress
      SubnetId: !ImportValue intra-vpc-Subnet1
      SecurityGroupIds:
        - !Ref SecurityGroup
      BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
            VolumeType: gp3
            VolumeSize: 30
