AWSTemplateFormatVersion: 2010-09-09

Parameters:
  VpcName:
    Type: String
    Default: multicidr-vpc

Resources:
  TransitGatewayIntraVPCAttachment:
    Type: AWS::EC2::TransitGatewayVpcAttachment
    Properties:
      TransitGatewayId: !ImportValue intra-vpc-TransitGateway
      VpcId: !ImportValue multicidr-vpc-VPC
      SubnetIds:
        - !ImportValue multicidr-vpc-IntraSubnet1AZ1
        - !ImportValue multicidr-vpc-IntraSubnet1AZ2
      Tags:
        - Key: Name
          Value: intra-transit-gateway-multicidr-attachment

  RouteTableForIntraSubnet2:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !ImportValue multicidr-vpc-VPC
      Tags:
        - Key: Name
          Value: !Sub ${VpcName}-route-table-intra-subnet2-${AWS::Region}

  RouteTableForIntraSubnet2RouteToTransitGateway:
    DependsOn:
      - TransitGatewayIntraVPCAttachment
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref RouteTableForIntraSubnet2
      DestinationCidrBlock: 0.0.0.0/0
      TransitGatewayId: !ImportValue intra-vpc-TransitGateway

  RouteTableAssociationForIntraSubnet2AZ1:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref RouteTableForIntraSubnet2
      SubnetId: !ImportValue multicidr-vpc-IntraSubnet2AZ1

  RouteTableAssociationForIntraSubnet2AZ2:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref RouteTableForIntraSubnet2
      SubnetId: !ImportValue multicidr-vpc-IntraSubnet2AZ2

