AWSTemplateFormatVersion: 2010-09-09

Parameters:
  TgwName:
    Type: String
    Default: transit-gateway

Resources:
  TransitGateway:
    Type: AWS::EC2::TransitGateway
    Properties:
      AutoAcceptSharedAttachments: disable
      DefaultRouteTableAssociation: disable
      DefaultRouteTablePropagation: disable
      VpnEcmpSupport: enable
      DnsSupport: enable
      Tags:
        - Key: Name
          Value: !Sub ${TgwName}

  TransitGatewayVpcAttachmentIntraVpc:
    Type: AWS::EC2::TransitGatewayVpcAttachment
    Properties:
      TransitGatewayId: !Ref TransitGateway
      VpcId: !ImportValue intra-vpc-VPC
      SubnetIds:
        - !ImportValue intra-vpc-Subnet1
      Tags:
        - Key: Name
          Value: !Sub ${TgwName}-intra-attachment

  TransitGatewayVpcAttachmentIntraVpcRouteTableAssociation:
    Type: AWS::EC2::TransitGatewayRouteTableAssociation
    Properties:
      TransitGatewayAttachmentId: !Ref TransitGatewayVpcAttachmentIntraVpc
      TransitGatewayRouteTableId: !Ref TransitGatewayIngressRouteTable

  TransitGatewayVpcAttachmentMulticidrVpc:
    Type: AWS::EC2::TransitGatewayVpcAttachment
    Properties:
      TransitGatewayId: !Ref TransitGateway
      VpcId: !ImportValue multicidr-vpc-VPC
      SubnetIds:
        - !ImportValue multicidr-vpc-IntraSubnet1AZ1
        - !ImportValue multicidr-vpc-IntraSubnet1AZ2
      Tags:
        - Key: Name
          Value: !Sub ${TgwName}-multicidr-attachment

  TransitGatewayVpcAttachmentMulticidrVpcRouteTableAssociation:
    Type: AWS::EC2::TransitGatewayRouteTableAssociation
    Properties:
      TransitGatewayAttachmentId: !Ref TransitGatewayVpcAttachmentMulticidrVpc
      TransitGatewayRouteTableId: !Ref TransitGatewayEgressRouteTable

  TransitGatewayEgressRouteTable:
    Type: AWS::EC2::TransitGatewayRouteTable
    Properties:
      TransitGatewayId: !Ref TransitGateway
      Tags:
        - Key: Name
          Value: !Sub ${TgwName}-egress-route-table

  TransitGatewayEgressRouteTableIntraRoute:
    Type: AWS::EC2::TransitGatewayRoute
    Properties:
      TransitGatewayRouteTableId: !Ref TransitGatewayEgressRouteTable
      DestinationCidrBlock: 172.16.0.0/16
      TransitGatewayAttachmentId: !Ref TransitGatewayVpcAttachmentIntraVpc

  TransitGatewayEgressRouteTableARoute:
    Type: AWS::EC2::TransitGatewayRoute
    Properties:
      TransitGatewayRouteTableId: !Ref TransitGatewayEgressRouteTable
      DestinationCidrBlock: 10.0.0.0/8
      Blackhole: true

  TransitGatewayEgressRouteTableCGNRoute:
    Type: AWS::EC2::TransitGatewayRoute
    Properties:
      TransitGatewayRouteTableId: !Ref TransitGatewayEgressRouteTable
      DestinationCidrBlock: 100.64.0.0/10
      Blackhole: true

  TransitGatewayEgressRouteTableBRoute:
    Type: AWS::EC2::TransitGatewayRoute
    Properties:
      TransitGatewayRouteTableId: !Ref TransitGatewayEgressRouteTable
      DestinationCidrBlock: 172.16.0.0/12
      Blackhole: true

  TransitGatewayEgressRouteTableCRoute:
    Type: AWS::EC2::TransitGatewayRoute
    Properties:
      TransitGatewayRouteTableId: !Ref TransitGatewayEgressRouteTable
      DestinationCidrBlock: 192.168.0.0/16
      Blackhole: true

  TransitGatewayEgressRouteTableInternetRoute:
    Type: AWS::EC2::TransitGatewayRoute
    Properties:
      TransitGatewayRouteTableId: !Ref TransitGatewayEgressRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      TransitGatewayAttachmentId: !Ref TransitGatewayVpcAttachmentIntraVpc

  TransitGatewayIngressRouteTable:
    Type: AWS::EC2::TransitGatewayRouteTable
    Properties:
      TransitGatewayId: !Ref TransitGateway
      Tags:
        - Key: Name
          Value: !Sub ${TgwName}-ingress-route-table


  TransitGatewayIngressRouteTableIntraRoute:
    Type: AWS::EC2::TransitGatewayRoute
    Properties:
      TransitGatewayRouteTableId: !Ref TransitGatewayIngressRouteTable
      DestinationCidrBlock: 172.16.0.0/16
      TransitGatewayAttachmentId: !Ref TransitGatewayVpcAttachmentIntraVpc

  TransitGatewayIngressRouteTableMulticidrRoute1:
    Type: AWS::EC2::TransitGatewayRoute
    Properties:
      TransitGatewayRouteTableId: !Ref TransitGatewayIngressRouteTable
      DestinationCidrBlock: 10.0.0.0/16
      TransitGatewayAttachmentId: !Ref TransitGatewayVpcAttachmentMulticidrVpc

  TransitGatewayIngressRouteTableMulticidrRoute2:
    Type: AWS::EC2::TransitGatewayRoute
    Properties:
      TransitGatewayRouteTableId: !Ref TransitGatewayIngressRouteTable
      DestinationCidrBlock: 100.64.2.0/24
      TransitGatewayAttachmentId: !Ref TransitGatewayVpcAttachmentMulticidrVpc

  IntraVpcPublicSubnetRouteForIntraVPCA:
    DependsOn:
      - TransitGatewayVpcAttachmentIntraVpc
    Type: AWS::EC2::Route
    Properties:
      DestinationCidrBlock: 10.0.0.0/8
      RouteTableId: !ImportValue intra-vpc-RouteTableForPublicSubnet
      TransitGatewayId: !Ref TransitGateway

  IntraVpcSubnet1RouteForIntraVPCA:
    DependsOn:
      - TransitGatewayVpcAttachmentIntraVpc
    Type: AWS::EC2::Route
    Properties:
      DestinationCidrBlock: 10.0.0.0/8
      RouteTableId: !ImportValue intra-vpc-RouteTableForSubnet1
      TransitGatewayId: !Ref TransitGateway

  IntraVpcPublicSubnetRouteForIntraVPCB:
    DependsOn:
      - TransitGatewayVpcAttachmentIntraVpc
    Type: AWS::EC2::Route
    Properties:
      DestinationCidrBlock: 172.16.0.0/12
      RouteTableId: !ImportValue intra-vpc-RouteTableForPublicSubnet
      TransitGatewayId: !Ref TransitGateway

  IntraVpcSubnet1RouteForIntraVPCB:
    DependsOn:
      - TransitGatewayVpcAttachmentIntraVpc
    Type: AWS::EC2::Route
    Properties:
      DestinationCidrBlock: 172.16.0.0/12
      RouteTableId: !ImportValue intra-vpc-RouteTableForSubnet1
      TransitGatewayId: !Ref TransitGateway

  IntraVpcPublicSubnetRouteForIntraVPCC:
    DependsOn:
      - TransitGatewayVpcAttachmentIntraVpc
    Type: AWS::EC2::Route
    Properties:
      DestinationCidrBlock: 192.168.0.0/16
      RouteTableId: !ImportValue intra-vpc-RouteTableForPublicSubnet
      TransitGatewayId: !Ref TransitGateway

  IntraVpcSubnet1RouteForIntraVPCC:
    DependsOn:
      - TransitGatewayVpcAttachmentIntraVpc
    Type: AWS::EC2::Route
    Properties:
      DestinationCidrBlock: 192.168.0.0/16
      RouteTableId: !ImportValue intra-vpc-RouteTableForSubnet1
      TransitGatewayId: !Ref TransitGateway

  IntraVpcPublicSubnetRouteForIntraVPCCGN:
    DependsOn:
      - TransitGatewayVpcAttachmentIntraVpc
    Type: AWS::EC2::Route
    Properties:
      DestinationCidrBlock: 100.64.0.0/10
      RouteTableId: !ImportValue intra-vpc-RouteTableForPublicSubnet
      TransitGatewayId: !Ref TransitGateway

  IntraVpcSubnet1RouteForIntraVPCCGN:
    DependsOn:
      - TransitGatewayVpcAttachmentIntraVpc
    Type: AWS::EC2::Route
    Properties:
      DestinationCidrBlock: 100.64.0.0/10
      RouteTableId: !ImportValue intra-vpc-RouteTableForSubnet1
      TransitGatewayId: !Ref TransitGateway

  RouteTableForMulticidrVpc:
    DependsOn:
      - TransitGatewayVpcAttachmentMulticidrVpc
    Type: AWS::EC2::Route
    Properties:
      DestinationCidrBlock: 0.0.0.0/0
      RouteTableId: !ImportValue multicidr-vpc-RouteTableForIntraSubnet
      TransitGatewayId: !Ref TransitGateway

Outputs:
  TransitGateway:
    Description: A reference to the transit gateway
    Value: !Ref TransitGateway
    Export:
      Name: !Sub ${AWS::StackName}-TransitGateway
