AWSTemplateFormatVersion: 2010-09-09

Parameters:
  TgwName:
    Type: String
    Default: transit-gateway

Resources:
  TransitGateway:
    Type: AWS::EC2::TransitGateway
    Properties:
      AutoAcceptSharedAttachments: enable
      DefaultRouteTableAssociation: enable
      DefaultRouteTablePropagation: enable
      VpnEcmpSupport: enable
      DnsSupport: enable
      Tags:
        - Key: Name
          Value: !Sub ${TgwName}

  TransitGatewayVpcAttachmentIntraVpc:
    Type: AWS::EC2::TransitGatewayVpcAttachment
    Properties:
      TransitGatewayId: !Ref TransitGateway
      VpcId: !ImportValue intra-vpc-VPC
      SubnetIds:
        - !ImportValue intra-vpc-Subnet1
      Tags:
        - Key: Name
          Value: !Sub ${TgwName}-intra-attachment

  TransitGatewayVpcAttachmentMulticidrVpc:
    Type: AWS::EC2::TransitGatewayVpcAttachment
    Properties:
      TransitGatewayId: !Ref TransitGateway
      VpcId: !ImportValue multicidr-vpc-VPC
      SubnetIds:
        - !ImportValue multicidr-vpc-IntraSubnet1AZ1
        - !ImportValue multicidr-vpc-IntraSubnet1AZ2
      Tags:
        - Key: Name
          Value: !Sub ${TgwName}-multicidr-attachment

  RouteTableRouteForIntraVPCA:
    DependsOn:
      - TransitGatewayVpcAttachmentIntraVpc
    Type: AWS::EC2::Route
    Properties:
      DestinationCidrBlock: 10.0.0.0/8
      RouteTableId: !ImportValue intra-vpc-RouteTableForSubnet1
      TransitGatewayId: !Ref TransitGateway

  RouteTableRouteForIntraVPCB:
    DependsOn:
      - TransitGatewayVpcAttachmentIntraVpc
    Type: AWS::EC2::Route
    Properties:
      DestinationCidrBlock: 172.16.0.0/12
      RouteTableId: !ImportValue intra-vpc-RouteTableForSubnet1
      TransitGatewayId: !Ref TransitGateway

  RouteTableRouteForIntraVPCC:
    DependsOn:
      - TransitGatewayVpcAttachmentIntraVpc
    Type: AWS::EC2::Route
    Properties:
      DestinationCidrBlock: 192.168.0.0/16
      RouteTableId: !ImportValue intra-vpc-RouteTableForSubnet1
      TransitGatewayId: !Ref TransitGateway

  RouteTableRouteForIntraVPCCGN:
    DependsOn:
      - TransitGatewayVpcAttachmentIntraVpc
    Type: AWS::EC2::Route
    Properties:
      DestinationCidrBlock: 100.64.0.0/10
      RouteTableId: !ImportValue intra-vpc-RouteTableForSubnet1
      TransitGatewayId: !Ref TransitGateway

  RouteTableForMulticidrVpc:
    DependsOn:
      - TransitGatewayVpcAttachmentMulticidrVpc
    Type: AWS::EC2::Route
    Properties:
      DestinationCidrBlock: 0.0.0.0/0
      RouteTableId: !ImportValue multicidr-vpc-RouteTableForIntraSubnet
      TransitGatewayId: !Ref TransitGateway

Outputs:
  TransitGateway:
    Description: A reference to the transit gateway
    Value: !Ref TransitGateway
    Export:
      Name: !Sub ${AWS::StackName}-TransitGateway
