AWSTemplateFormatVersion: 2010-09-09

Parameters:
  VpcName:
    Type: String
    Default: vpc-multiple-cidr

  VpcIntraCIDR:
    Type: String
    Default: 100.64.2.0/24

  IntraSubnet1AZ1CIDR:
    Type: String
    Default: 100.64.2.0/28

  IntraSubnet1AZ2CIDR:
    Type: String
    Default: 100.64.2.16/28

  IntraSubnet2AZ1CIDR:
    Type: String
    Default: 100.64.2.128/27

  IntraSubnet2AZ2CIDR:
    Type: String
    Default: 100.64.2.160/27

Resources:
  VpcIntraCidrBlock:
    Type: AWS::EC2::VPCCidrBlock
    Properties:
      VpcId: !ImportValue vpc-multiple-cidr-VPC
      CidrBlock: !Ref VpcIntraCIDR

  IntraSubnet1AZ1:
    DependsOn:
      - VpcIntraCidrBlock
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !ImportValue vpc-multiple-cidr-VPC
      AvailabilityZone: !Select [0, !GetAZs ""]
      CidrBlock: !Ref IntraSubnet1AZ1CIDR
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: !Sub ${VpcName}-intra-subnet1az1-${AWS::Region}

  IntraSubnet1AZ2:
    DependsOn:
      - VpcIntraCidrBlock
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !ImportValue vpc-multiple-cidr-VPC
      AvailabilityZone: !Select [1, !GetAZs ""]
      CidrBlock: !Ref IntraSubnet1AZ2CIDR
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: !Sub ${VpcName}-intra-subnet1az2-${AWS::Region}

  IntraSubnet2AZ1:
    DependsOn:
      - VpcIntraCidrBlock
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !ImportValue vpc-multiple-cidr-VPC
      AvailabilityZone: !Select [0, !GetAZs ""]
      CidrBlock: !Ref IntraSubnet2AZ1CIDR
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: !Sub ${VpcName}-intra-subnet2az1-${AWS::Region}

  IntraSubnet2AZ2:
    DependsOn:
      - VpcIntraCidrBlock
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !ImportValue vpc-multiple-cidr-VPC
      AvailabilityZone: !Select [1, !GetAZs ""]
      CidrBlock: !Ref IntraSubnet2AZ2CIDR
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: !Sub ${VpcName}-intra-subnet2az2-${AWS::Region}

  TransitGatewayIntraVPCAttachment:
    Type: AWS::EC2::TransitGatewayVpcAttachment
    Properties:
      TransitGatewayId: !ImportValue vpc-intra-TransitGateway
      VpcId: !ImportValue vpc-multiple-cidr-VPC
      SubnetIds:
        - !Ref IntraSubnet1AZ1
        - !Ref IntraSubnet1AZ2

  RouteTableForIntraSubnet2:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !ImportValue vpc-multiple-cidr-VPC
      Tags:
        - Key: Name
          Value: !Sub ${VpcName}-route-table-intra-subnet2-${AWS::Region}

  RouteTableForIntraSubnet2RouteToTransitGateway:
    DependsOn:
      - TransitGatewayIntraVPCAttachment
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref RouteTableForIntraSubnet2
      DestinationCidrBlock: 0.0.0.0/0
      TransitGatewayId: !ImportValue vpc-intra-TransitGateway

  RouteTableAssociationForIntraSubnet2AZ1:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref RouteTableForIntraSubnet2
      SubnetId: !Ref IntraSubnet2AZ1

  RouteTableAssociationForIntraSubnet2AZ2:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref RouteTableForIntraSubnet2
      SubnetId: !Ref IntraSubnet2AZ2

Outputs:
  IntraSubnet1AZ1:
    Description: A reference to the created IntraSubnet1AZ1
    Value: !Ref IntraSubnet1AZ1
    Export:
      Name: !Sub ${AWS::StackName}-IntraSubnet1AZ1

  IntraSubnet1AZ2:
    Description: A reference to the created IntraSubnet1AZ2
    Value: !Ref IntraSubnet1AZ2
    Export:
      Name: !Sub ${AWS::StackName}-IntraSubnet1AZ2

  IntraSubnet2AZ1:
    Description: A reference to the created IntraSubnet2AZ1
    Value: !Ref IntraSubnet2AZ1
    Export:
      Name: !Sub ${AWS::StackName}-IntraSubnet2AZ1

  IntraSubnet2AZ2:
    Description: A reference to the created IntraSubnet2AZ2
    Value: !Ref IntraSubnet2AZ2
    Export:
      Name: !Sub ${AWS::StackName}-IntraSubnet2AZ2
