AWSTemplateFormatVersion: 2010-09-09

Parameters:
  VpcName:
    Type: String
    Default: vpc-intra

  VpcCIDR:
    Type: String
    Default: 172.16.0.0/16

  Subnet1CIDR:
    Type: String
    Default: 172.16.0.0/16

  OggInstanceIpAddress:
    Type: String
    Default: 172.16.0.4

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCIDR
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: !Sub ${VpcName}-${AWS::Region}


  Subnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [0, !GetAZs ""]
      CidrBlock: !Ref Subnet1CIDR
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: ${VpcName}-subnet1-${AWS::Region}

  IntraRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub ${VpcName}-route-${AWS::Region}

  SubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref IntraRouteTable
      SubnetId: !Ref Subnet1

  OggInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-087bd73fc10ea41af
      InstanceType: t2.micro
      PrivateIpAddress: !Ref OggInstanceIpAddress
      SubnetId: !Ref Subnet1
      BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
            VolumeType: gp3
            DeleteOnTermination: false
            VolumeSize: 250

Outputs:
  VPC:
    Description: A reference to the created VPC
    Value: !Ref VPC

  Subnet1:
    Description: A reference to the subnet
    Value: !Join [",", [!Ref Subnet1]]
