AWSTemplateFormatVersion: 2010-09-09

Parameters:
  OggInstanceIpAddress:
    Type: String
    Default: 100.64.2.132

Resources:
  OggInstanceKeyPair:
    Type: AWS::EC2::KeyPair
    Properties: 
      KeyName: !Sub ${AWS::StackName}-OggInstanceKeyPair

  OggInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-087bd73fc10ea41af
      InstanceType: t2.micro
      KeyName: !Ref OggInstanceKeyPair
      PrivateIpAddress: !Ref OggInstanceIpAddress
      SubnetId: !ImportValue vpc-multiple-cidr-intra-connection-IntraSubnet2AZ1
      BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
            VolumeType: gp3
            DeleteOnTermination: false
            VolumeSize: 250
