AWSTemplateFormatVersion: 2010-09-09

Parameters:
  VpcName:
    Type: String
    Default: vpc-intra

  VpcCIDR:
    Type: String
    Default: 172.16.0.0/16

  Subnet1CIDR:
    Type: String
    Default: 172.16.0.0/16

  OggInstanceIpAddress:
    Type: String
    Default: 172.16.0.4

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCIDR
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: !Sub ${VpcName}-${AWS::Region}

  Subnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [0, !GetAZs ""]
      CidrBlock: !Ref Subnet1CIDR
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: !Sub ${VpcName}-subnet1-${AWS::Region}

  IntraRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub ${VpcName}-route-${AWS::Region}

  SubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref IntraRouteTable
      SubnetId: !Ref Subnet1

  TransitGateway:
    Type: AWS::EC2::TransitGateway
    Properties:
      AutoAcceptSharedAttachments: enable
      DefaultRouteTableAssociation: enable
      DefaultRouteTablePropagation: enable
      VpnEcmpSupport: enable
      DnsSupport: enable
      Tags:
        - Key: Name
          Value: intra-transit-gateway

  TransitGatewayIntraVPCAttachment:
    Type: AWS::EC2::TransitGatewayVpcAttachment
    Properties:
      SubnetIds:
        - !Ref Subnet1
      TransitGatewayId: !Ref TransitGateway
      VpcId: !Ref VPC

  TransitGatewayIntraRouteTable:
    Type: AWS::EC2::TransitGatewayRouteTable
    Properties:
      TransitGatewayId: !Ref TransitGateway
      Tags:
        - Key: Name
          Value: intra-transit-gateway-intra-route-table

  TransitGatewayCloudRouteTable:
    Type: AWS::EC2::TransitGatewayRouteTable
    Properties:
      TransitGatewayId: !Ref TransitGateway
      Tags:
        - Key: Name
          Value: intra-transit-gateway-cloud-route-table

  TransitGatewayCloudRouteToIntraVPC:
    Type: AWS::EC2::TransitGatewayRoute
    Properties:
      TransitGatewayRouteTableId: !Ref TransitGatewayCloudRouteTable
      DestinationCidrBlock: !Ref VpcCIDR
      TransitGatewayAttachmentId: !Ref TransitGatewayIntraVPCAttachment

  IntraRouteTableRouteToTransitGateway:
    Type: AWS::EC2::Route
    Properties:
      DestinationCidrBlock: 0.0.0.0/0
      RouteTableId: !Ref IntraRouteTable
      TransitGatewayId: !Ref TransitGateway

  VPCEndpointSSM:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      PrivateDnsEnabled: true
      ServiceName: !Sub com.amazonaws.${AWS::Region}.ssm
      SubnetIds:
        - !Ref Subnet1
      VpcEndpointType: Interface
      VpcId: !Ref VPC

  EndpointSSMMessages:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      PrivateDnsEnabled: true
      ServiceName: !Sub com.amazonaws.${AWS::Region}.ssmmessages
      SubnetIds:
        - !Ref Subnet1
      VpcEndpointType: Interface
      VpcId: !Ref VPC

  EndpointEC2Messages:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      PrivateDnsEnabled: true
      ServiceName: !Sub com.amazonaws.${AWS::Region}.ec2messages
      SubnetIds:
        - !Ref Subnet1
      VpcEndpointType: Interface
      VpcId: !Ref VPC

  EndpointS3:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      RouteTableIds:
        - !Ref IntraRouteTable
      ServiceName: !Sub com.amazonaws.${AWS::Region}.s3
      VpcEndpointType: Gateway
      VpcId: !Ref VPC

  EC2IAMRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore

  EC2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles:
        - !Ref EC2IAMRole

  OggInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-087bd73fc10ea41af
      InstanceType: t2.micro
      IamInstanceProfile: !Ref EC2InstanceProfile
      PrivateIpAddress: !Ref OggInstanceIpAddress
      SubnetId: !Ref Subnet1
      BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
            VolumeType: gp3
            DeleteOnTermination: false
            VolumeSize: 250

Outputs:
  VPC:
    Description: A reference to the created VPC
    Value: !Ref VPC

  Subnet1:
    Description: A reference to the subnet
    Value: !Join [",", [!Ref Subnet1]]
